version: '3.8'

services:
  # Service pour MySQL
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neo_egoist_league
      MYSQL_USER: ego
      MYSQL_PASSWORD: Jinpachi
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Service pour phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

  # Service pour le serveur PHP
  php:
    build: .
    container_name: php
    restart: always
    volumes:
      - ./src/public:/var/www/html
      - ./src/images:/var/www/html/images
      - ./src/app:/var/www/app
    ports:
      - "8080:80"
    depends_on:
      - db

# Réseau par défaut, ajustez selon vos besoins
networks:
  default:
    external: true
    name: mynetwork
